spring:
  application:
        name: taco-cloud
  datasource:
    url: jdbc:postgresql://localhost:5432/taco-cloud
    username: gusainov
    password: 8889893567
  data:
      mongodb:
        host: localhost
        port: 27017
        database: tacoclouddb