spring:
  application:
        name: taco-cloud

  datasource:
        generate-unique-name: false
        name: tacocloud
#  cassandra:
#    keyspace-name: taco_Cloud
#    schema-action: recreate
#    local-datacenter: datacenter1
#    username: tacocloud
#    password: s3cr3tP455w0rd
  data:
      mongodb:
        host: mongodb.tacocloud.com
        port: 27017
        username: tacocloud
        password: s3cr3tp455w0rd
        database: tacoclouddb